# Generated by Django 4.2.6 on 2023-10-31 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_code', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, max_length=255, null=True)),
                ('End_date', models.DateField(blank=True, max_length=255, null=True)),
                ('gst_type', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='image/patient')),
                ('superadmin_approval', models.IntegerField(default=0, null=True)),
                ('Distributor_approval', models.IntegerField(default=0, null=True)),
                ('reg_action', models.CharField(blank=True, default='self', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='payment_terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms_number', models.IntegerField(blank=True, null=True)),
                ('payment_terms_value', models.CharField(blank=True, max_length=100, null=True)),
                ('days', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='staff_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='image/staff')),
                ('Action', models.IntegerField(default=0, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='modules_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_invoice', models.CharField(default=0, max_length=100, null=True)),
                ('Estimate', models.IntegerField(default=0, null=True)),
                ('Payment_in', models.IntegerField(default=0, null=True)),
                ('sales_order', models.IntegerField(default=0, null=True)),
                ('Delivery_challan', models.IntegerField(default=0, null=True)),
                ('sales_return', models.IntegerField(default=0, null=True)),
                ('Purchase_bills', models.IntegerField(default=0, null=True)),
                ('Payment_out', models.IntegerField(default=0, null=True)),
                ('Purchase_order', models.IntegerField(default=0, null=True)),
                ('Purchase_return', models.IntegerField(default=0, null=True)),
                ('Bank_account', models.IntegerField(default=0, null=True)),
                ('Cash_in_hand', models.IntegerField(default=0, null=True)),
                ('cheques', models.IntegerField(default=0, null=True)),
                ('Loan_account', models.IntegerField(default=0, null=True)),
                ('update_action', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(default='New', max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Distributors_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='image/distributor')),
                ('start_date', models.DateField(blank=True, max_length=255, null=True)),
                ('End_date', models.DateField(blank=True, max_length=255, null=True)),
                ('Log_Action', models.IntegerField(default=0, null=True)),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.payment_terms')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='Distributors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.distributors_details'),
        ),
        migrations.AddField(
            model_name='company',
            name='dateperiod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.payment_terms'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
