# Generated by Django 4.2.6 on 2023-11-03 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vyaparapp', '0005_unitmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(max_length=255)),
                ('trans_invoice', models.PositiveBigIntegerField(default=0)),
                ('trans_name', models.CharField(max_length=255)),
                ('trans_date', models.DateTimeField()),
                ('trans_qty', models.PositiveBigIntegerField(default=0)),
                ('trans_price', models.PositiveBigIntegerField(default=0)),
                ('trans_status', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
