# Generated by Django 4.2.6 on 2023-11-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0007_alter_transactionmodel_trans_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='trans_name',
            new_name='trans_user_name',
        ),
    ]
