# Generated by Django 4.2.6 on 2023-11-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0008_rename_trans_name_transactionmodel_trans_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='trans_created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
