# Generated by Django 4.2.6 on 2023-11-03 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0009_transactionmodel_trans_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.itemmodel'),
        ),
    ]
