# Generated by Django 4.2.6 on 2023-11-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0010_transactionmodel_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='trans_current_qty',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
