# Generated by Django 4.2.6 on 2023-11-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0011_transactionmodel_trans_current_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='trans_adjusted_qty',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
