# Generated by Django 4.2.6 on 2023-11-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0012_transactionmodel_trans_adjusted_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='item_current_stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
